### ISSUE TITLE
"reply-to" instead of "from"

### ISSUE THREAD

**Issue by bobpassaro** [mzur/kirby-contact-form#21]
In the sendForm method (line 223) wouldn't it be better to have the submitter's email address entered in a "Reply-To" line in the header as opposed to being used directly in the "From" line? The "From" line should actually be the domain the form is running on, no?

I was having some trouble with the plugin not reliably delivering some emails (especially when the submitter was using a gmail address, for instance). I think receiving servers were seeing a gmail "From" address and realizing the IP was not gmail, so they got suspicious and didn't deliver it. But I don't think this problem would necessarily be isolated to gmail.

fyi, the failed mail sent me to this link for more info: http://dhurl.org/20b

If I have some time, I may fork and test this. I'll keep you posted.

**Comment by bobpassaro** [comment]
This is working better -- with a 'replyTo' line added into the params array right after the "from" line.

Mail is now seems to be being delivered reliably with this form -- including gmail from-addresses. And can still reply to the sender by clicking "reply". However, I'm not getting the 'name' to show up in either of these for some reason. I'm not super familiar with Kirby, so I'm not 100% sure how this is working. That would be preferable to get the send name to show in the "from" line with the host domain. I just hardcoded the hosting domain for a quick fix, but it would be best to make that dynamic obviously -- one of the kirby url functions maybe with preg replace or something?

    'from'        =>   a::get($this->data, 'name', '') . ' <admin@the-hosting-domain.com>',
    'replyTo'   =>   a::get($this->data, 'name', '') . ' <' . a::get($this->data, '_from') . '>',

Thanks for your great work on this plugin. I realize I may be missing something that caused me to have this problem in the first place -- and you've dealt with it in some way that I don't see here.

**Comment by mzur** [comment]
I totally agree, `replyTo` would be a better field for the submitter's email address. I'd prefer not to generate the `from` address directly from the domain name since the user should decide which of their email adresses they want to take. It can be an additional (required) argument in the email array.

As to why the name does not appear I found that it is [intentionally removed](https://github.com/getkirby/toolkit/blob/f79c205d8fa5efc59cc451cec7b09faa70976f37/lib/email.php#L33) by the Email class. I guess we could open an issue at the toolkit repo and ask if this can be fixed or we could write our own email service that adds the name to the header again.

**Comment by mzur** [comment]
Opened a new issure for the names.

**Comment by bobpassaro** [comment]
Thanks, Martin. This looks good to me -- handling the sender in the setup array to give users some flexibility.
